name: Bingo
version: 2.0
main: annie312.bingo.Bingo
api-version: '1.21'

commands:
  bingo:
    description: Bingo command
    usage: /bingo
    permission: bingo.admin

permissions:
  bingo.admin:
    default: op